triggers:
- cron:
    spec: 0,15,30,45 * * * *
    entryPoint: cronjob1
#to start concord run command docker-compose up
configuration:
  runtime: concord-v2
  dependencies:
  - "mvn://org.python:jython-standalone:2.7.2"

flows:
  default:
  - log: "Hello Concord User v2"
  - script: js
    body: |
      execution.variables().set('myVar', 'Hello, world!');
  - log: "js output: ${myVar}"

  - script: python
    body: |
      from java.util import HashMap, ArrayList

      aDict = {'x': 123}
      aList = [1, 2, 3]

      execution.setVariable('aDict', HashMap(aDict))
      execution.setVariable('aList', ArrayList(aList))
      execution.variables().set('aDict', HashMap(aDict));
      execution.variables().set('aList', ArrayList(aList));

      x = 2 * 3;
      print ("py x", x)
      execution.variables().set('result', x);

  - log: "python out: ${result}"
  - log: "aDict  : ${aDict}"
  - log: "aList  : ${aList}"


  cronjob1:
  - log: "Trigger  cronjob1"
  - call: cronjob2


  cronjob2:
  - log: "Trigger  cronjob2"
