triggers:
- cron:
    spec: 0,15,30,45 * * * *
    entryPoint: cronjob1

configuration:
  runtime: concord-v2

flows:
  default:
  - log: "Hello Concord User v2"
  - script: js
    body: |
      execution.variables().set('myVar', 'Hello, world!');
  - log: "js output: ${myVar}"

  cronjob1:
  - log: "Trigger  cronjob1"
  - call: cronjob2


  cronjob2:
  - log: "Trigger  cronjob2"
